import type { Resource } from "./contracts";
export const navigation: { id: Resource; label: string; group: string }[] = [
  { id: "dashboard", label: "总览", group: "工作台" },
  { id: "users", label: "用户", group: "工作台" },
  { id: "beta-applications", label: "内测申请", group: "工作台" },
  { id: "invitations", label: "邀请码", group: "工作台" },
  { id: "entitlements", label: "会员与额度", group: "运营" },
  { id: "ai-usage", label: "AI 用量", group: "运营" },
  { id: "email", label: "邮件", group: "运营" },
  { id: "feedback", label: "反馈与举报", group: "运营" },
  { id: "bans", label: "风控与封禁", group: "运营" },
  { id: "analytics", label: "商业分析", group: "系统" },
  { id: "infrastructure", label: "基础设施", group: "系统" },
  { id: "deployments", label: "版本与部署", group: "系统" },
  { id: "audit", label: "审计日志", group: "系统" },
  { id: "settings", label: "设置", group: "系统" },
];
export const columns: Partial<Record<Resource, [string, string][]>> = {
  users: [
    ["email", "邮箱"],
    ["name", "用户名"],
    ["createdAt", "注册时间"],
    ["lastActiveAt", "最后活跃"],
    ["cohort", "内测批次"],
    ["inviteCode", "邀请码"],
    ["membershipStatus", "会员状态"],
    ["aiUsed", "AI 本月用量"],
    ["accountStatus", "账号状态"],
  ],
  "beta-applications": [
    ["name", "姓名"],
    ["email", "邮箱"],
    ["organization", "机构"],
    ["role", "身份"],
    ["useCase", "使用场景"],
    ["source", "来源"],
    ["createdAt", "提交时间"],
    ["status", "状态"],
  ],
  invitations: [
    ["code", "邀请码"],
    ["cohort", "内测批次"],
    ["kind", "类型"],
    ["status", "状态"],
    ["used", "已使用"],
    ["limit", "上限"],
    ["expiresAt", "过期时间"],
    ["createdAt", "创建时间"],
    ["source", "来源"],
    ["note", "备注"],
  ],
  entitlements: [
    ["email", "邮箱"],
    ["source", "授权来源"],
    ["effectivePlus", "VD Plus 生效"],
    ["validUntil", "有效截止"],
    ["status", "状态"],
    ["reason", "原因"],
  ],
  quotas: [
    ["email", "邮箱"],
    ["policy", "额度策略"],
    ["limit", "额度"],
    ["used", "已使用"],
    ["remaining", "剩余"],
    ["resetAt", "重置时间"],
  ],
  bans: [
    ["email", "邮箱"],
    ["accountStatus", "账号状态"],
    ["reason", "原因"],
    ["actor", "操作人"],
    ["createdAt", "创建时间"],
    ["expiresAt", "截止时间"],
    ["note", "备注"],
  ],
  audit: [
    ["actor", "操作人"],
    ["action", "操作"],
    ["target", "目标"],
    ["reason", "原因"],
    ["before", "变更前"],
    ["after", "变更后"],
    ["timestamp", "时间"],
    ["requestId", "请求 ID"],
  ],
  "ai-usage": [
    ["email", "邮箱"],
    ["model", "模型"],
    ["inputTokens", "输入 tokens"],
    ["outputTokens", "输出 tokens"],
    ["estimatedCost", "预估费用"],
    ["latencyMs", "延迟 / ms"],
    ["status", "状态"],
    ["createdAt", "时间"],
  ],
  email: [
    ["template", "模板"],
    ["recipient", "收件人"],
    ["status", "状态"],
    ["providerMessageId", "Resend 消息 ID"],
    ["createdAt", "发送时间"],
    ["deliveredAt", "送达时间"],
    ["bounce", "退信"],
    ["complaint", "投诉"],
  ],
  feedback: [
    ["kind", "类型"],
    ["email", "用户邮箱"],
    ["category", "分类"],
    ["status", "状态"],
    ["createdAt", "提交时间"],
    ["caseReference", "工单编号"],
  ],
  deployments: [
    ["provider", "平台"],
    ["commit", "提交"],
    ["status", "状态"],
    ["environment", "环境"],
    ["createdAt", "部署时间"],
  ],
};
export const metrics: { group: string; fields: [string, string][] }[] = [
  {
    group: "用户",
    fields: [
      ["totalUsers", "总用户数"],
      ["newToday", "今日新增"],
      ["new7d", "7 日新增"],
      ["dau", "日活跃用户"],
      ["wau", "周活跃用户"],
      ["mau", "月活跃用户"],
    ],
  },
  {
    group: "内测",
    fields: [
      ["pendingApplications", "待审核申请"],
      ["approvedApplications", "已批准"],
      ["issuedInvites", "已发邀请码"],
      ["inviteUsageRate", "邀请码使用率"],
      ["inviteConversion", "邀请 → 注册转化率"],
    ],
  },
  {
    group: "会员",
    fields: [
      ["freeUsers", "免费用户"],
      ["plusUsers", "Plus 用户"],
      ["adminGrants", "管理员赠送会员"],
      ["expiringUsers", "即将到期用户"],
      ["activeSubscriptions", "Paddle 有效订阅"],
    ],
  },
  {
    group: "AI",
    fields: [
      ["callsToday", "今日调用量"],
      ["inputTokensToday", "今日输入 tokens"],
      ["outputTokensToday", "今日输出 tokens"],
      ["costToday", "今日预估费用"],
      ["costMonth", "本月预估费用"],
      ["failureRate", "失败率"],
      ["p50Latency", "p50 延迟"],
      ["p95Latency", "p95 延迟"],
    ],
  },
  {
    group: "待办",
    fields: [
      ["pendingFeedback", "待处理反馈"],
      ["pendingReports", "待处理举报"],
      ["bannedAccounts", "当前封禁账号"],
      ["recentErrors", "最近错误"],
    ],
  },
];
export const funnel = [
  "访问申请页",
  "提交申请",
  "批准",
  "发出邀请",
  "注册",
  "完成入门引导",
  "创建第一任务",
  "创建第一目标",
  "首次 AI",
  "首次回顾",
  "D1 留存",
  "D3 留存",
  "D7 留存",
  "Plus 转化",
];
